# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/property_lookup.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/property_lookup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/property_lookup.proto\"(\n\nZipRequest\x12\x0b\n\x03zip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"$\n\x0f\x41\x64\x64ressResponse\x12\x11\n\taddresses\x18\x01 \x03(\t2@\n\x0ePropertyLookup\x12.\n\x0bLookupByZip\x12\x0b.ZipRequest\x1a\x10.AddressResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.property_lookup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ZIPREQUEST']._serialized_start=31
  _globals['_ZIPREQUEST']._serialized_end=71
  _globals['_ADDRESSRESPONSE']._serialized_start=73
  _globals['_ADDRESSRESPONSE']._serialized_end=109
  _globals['_PROPERTYLOOKUP']._serialized_start=111
  _globals['_PROPERTYLOOKUP']._serialized_end=175
# @@protoc_insertion_point(module_scope)
